### ISSUE TITLE
Error:  Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by dgoryeo** [Vaibhavs10/insanely-fast-whisper#41]
I get the following error: 

`AssertionError: Torch not compiled with CUDA enabled`

Although I do have the` torch (2.1)`  and `cuda (12.1)` :

```
>>> print("PyTorch version:", torch.__version__)
PyTorch version: 2.1.0+cu121
>>> print("Is CUDA available:", torch.cuda.is_available())
Is CUDA available: True
>>>
```

```
>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:36:24_Pacific_Standard_Time_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
```

I run in conda env on Windows. My GPU is nvidia RTX3060 with the latest drivers.

**Comment by Vaibhavs10** [comment]
I'm sorry, I have minimal experience with Windows and CUDA. From what I've heard, you can set it up via WSL and it works perfectly!

Feel free to re-open this issue if you come across a fix!
