### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by pto2k** [Vaibhavs10/insanely-fast-whisper#54]
I installed it using pipx but I'm having this error running the tool.
How could I fix this? Do I need to install a proper version of Torch with pipx?

For context, I have the original Whisper installed with pip and it runs okay.

Thank you!

`D:\Tools\Whisper\Video>insanely-fast-whisper --file-name video.wav
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "C:\Users\andy\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\andy\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\andy\.local\bin\insanely-fast-whisper.exe\__main__.py", line 7, in <module>
  File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\insanely_fast_whisper\cli.py", line 86, in main
    pipe = pipeline(
  File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\transformers\pipelines\__init__.py", line 1070, in pipeline
    return pipeline_class(model=model, framework=framework, task=task, **kwargs)
  File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\transformers\pipelines\automatic_speech_recognition.py", line 239, in __init__
    self.model.to(device)
  File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\transformers\modeling_utils.py", line 2271, in to
    return super().to(*args, **kwargs)
  File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\torch\nn\modules\module.py", line 1160, in to
    return self._apply(convert)
  File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
  File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled`

**Comment by Vaibhavs10** [comment]
Hi @pto2k - This looks like an error with your CUDA installation. We install Torch along at the time of setup. https://github.com/Vaibhavs10/insanely-fast-whisper/blob/63ca79de29402821eac59bea2ea273fac4b028aa/pdm.lock#L1381

You might want to run it on a device with CUDA available (if you are on windows then through WSL)

Here's how you can run it via a Colab: https://github.com/Vaibhavs10/scratchpad/blob/main/insanely_fast_whisper_colab.ipynb

(closing this for now, feel free to re-open)

**Comment by jupiter909** [comment]
Am getting the same error.
Yet I can run this to confirm my torch cuda is installed I get the following.
```
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.cuda.get_device_name(0)
'NVIDIA GeForce RTX 3060'
```

**Comment by Vaibhavs10** [comment]
Could you give more info about your device/ os?

**Comment by jupiter909** [comment]
Here's the details of this machine:
Windows 10 - AMD Ryzen 9 7950X 16-Core Processor   4.50 GHz - 64GB - NVIDIA GeForce RTX 3060 12GB

Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
torch 2.1.1+cu121

**Comment by Vaibhavs10** [comment]
This is quite weird, I don't have access to a Windows machine. What do you get if you run `pipx run insanely-fast-whisper --file-name `

**Comment by jupiter909** [comment]
Unfortunately the same error. I'll try poke around in the week and see if I can figure this out. Thanks 🙏

**Comment by pto2k** [comment]
I tried manually installing Torch into the venv.
`python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121`

After that, previous error is replaced by the following message, but the program just keeps running with no more output:
```
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
The BetterTransformer implementation does not support padding during training, as the fused kernels do not support attention masks. Beware that passing padded batched data during training may result in unexpected outputs. Please refer to https://huggingface.co/docs/optimum/bettertransformer/overview for more details.
```

**Comment by Vaibhavs10** [comment]
@pto2k - Do you mind updating to the latest release please? it should be fixed now!
Note: You might still need to install torch manually in the venv.

Also, 
```
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
The BetterTransformer implementation does not support padding during training, as the fused kernels do not support attention masks. Beware that passing padded batched data during training may result in unexpected outputs. Please refer to https://huggingface.co/docs/optimum/bettertransformer/overview for more details.
```
This is not an error but a warning. We've added a progress bar to showcase that the transcription process is underway. That'll help reduce the ambiguity.

**Comment by lucasbr15** [comment]
> I installed it using pipx but I'm having this error running the tool. How could I fix this? Do I need to install a proper version of Torch with pipx?
> 
> For context, I have the original Whisper installed with pip and it runs okay.
> 
> Thank you!
> 
> `D:\Tools\Whisper\Video>insanely-fast-whisper --file-name video.wav Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained. Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained. Traceback (most recent call last): File "C:\Users\andy\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Users\andy\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "C:\Users\andy\.local\bin\insanely-fast-whisper.exe\__main__.py", line 7, in <module> File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\insanely_fast_whisper\cli.py", line 86, in main pipe = pipeline( File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\transformers\pipelines\__init__.py", line 1070, in pipeline return pipeline_class(model=model, framework=framework, task=task, **kwargs) File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\transformers\pipelines\automatic_speech_recognition.py", line 239, in __init__ self.model.to(device) File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\transformers\modeling_utils.py", line 2271, in to return super().to(*args, **kwargs) File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\torch\nn\modules\module.py", line 1160, in to return self._apply(convert) File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply module._apply(fn) File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply module._apply(fn) File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply module._apply(fn) File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\torch\nn\modules\module.py", line 833, in _apply param_applied = fn(param) File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\torch\nn\modules\module.py", line 1158, in convert return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking) File "C:\Users\andy\.local\pipx\venvs\insanely-fast-whisper\lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init raise AssertionError("Torch not compiled with CUDA enabled") AssertionError: Torch not compiled with CUDA enabled`

Same error Windows 11, Python 3.9.9

**Comment by pto2k** [comment]
Thank you for the update.  Voila!! It works now!

- Yes, do need to install the Torch manually again after updating IFW.
- That warning message was still shown.
- Transcribing a 48-minute mp3 file took 1min 13sec according to the progress bar on my 4070
- It took over a minute before the progression bar showed up. It'd be nice if there was some output for the activity too.
- The progression bar flashes nicely. Would it be possible to show the percentage with it?

And now I want to know: how do I convert the output.json into a SRT file to use with video players?

Thanks!

**Comment by Vaibhavs10** [comment]
Awesome! I'll add this to a FAQ on the Repo.

**Comment by jupiter909** [comment]
@Vaibhavs10 & @pto2k  Thanks it works now. 🥳

@pto2k To convert this output.json to SRT I quickly slapped this together, it seems to work. ymmv

`import json

def read_json_from_file(file_path):
    """Reads JSON data from a given file path."""
    with open(file_path, 'r') as file:
        data = json.load(file)
        return data.get("chunks", [])  # Access the 'chunks' attribute

def convert_to_srt_time(timestamp):
    """Converts a timestamp from seconds to SRT time format."""
    if timestamp is None:
        timestamp = 24 * 3600  # 24 hours in seconds
    hours = int(timestamp // 3600)
    minutes = int((timestamp % 3600) // 60)
    seconds = int(timestamp % 60)
    milliseconds = int((timestamp - int(timestamp)) * 1000)
    return f"{hours:02}:{minutes:02}:{seconds:02},{milliseconds:03}"

def convert_json_to_srt(subtitles):
    """Converts JSON subtitle data to SRT format."""
    srt_content = ""
    for i, subtitle in enumerate(subtitles, start=1):
        start_time, end_time = subtitle.get("timestamp", [None, None])
        srt_content += f"{i}\n"
        srt_content += f"{convert_to_srt_time(start_time)} --> {convert_to_srt_time(end_time)}\n"
        srt_content += f"{subtitle.get('text', '')}\n\n"
    return srt_content.strip()

# Assuming the file 'output.json' is present in the current directory
file_path = 'output.json'
try:
    json_data = read_json_from_file(file_path)
    srt_content = convert_json_to_srt(json_data)
    print(srt_content)
except Exception as e:
    print(f"An error occurred: {e}")
`

**Comment by Vaibhavs10** [comment]
This is now part of the [FAQs](https://github.com/Vaibhavs10/insanely-fast-whisper#frequently-asked-questions). Hence, closing this! Thank you all!
